# Generated by Django 4.0.4 on 2022-05-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=130)),
                ('Username', models.CharField(max_length=130)),
                ('Email', models.CharField(max_length=130)),
                ('Address', models.CharField(max_length=130)),
                ('Address2', models.CharField(max_length=130)),
                ('Name_on_card', models.CharField(max_length=130)),
                ('Credit_card_number', models.CharField(max_length=130)),
                ('Expiration', models.CharField(max_length=130)),
                ('CVV', models.CharField(max_length=3)),
            ],
        ),
    ]
